apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- ../../../bases/prometheus-agent

configMapGenerator:
- name: prometheus-agent-config
  namespace: monitoring
  files:
  - prometheus.yml
